### PR TITLE
[phx.gen.live] Extract Fixtures module

### PR DESCRIPTION
**Pull request by aaronrenner**
I'd like to get some feedback on these proposed updates to the `phx.gen.live` generators for 
https://github.com/phoenixframework/phoenix/issues/3797. The goal of this is to extract a `<Context>Fixtures` module into `test/support/fixtures` with functions that could be used throughout the test suite.

I'm not sure if extracting separate `*_attrs` functions in the Fixtures module is the way to go, but it does consolidate the `*_attrs` module variables in the different tests.

### CODE REVIEW

**Comment by josevalim** [comment]
Hi @aaronrenner! Thanks for the PR! I would honestly prefer to keep it simpler, as a single function with hardcoded values because in practice that’s what you need. The update and invalid values will often change as you expand things and try different scenarios, so I would prefer to keep them in their relative test files. To me, the most important in the fixture is the correct values, which we won’t have to repeat. :)

**Comment by aaronrenner** [comment]
@josevalim I just pushed an update to to simplify the fixture and have a single `DemoLiveApp.BlogFixtures.post_fixture/1` function. Just wanted to double-check this is what you're thinking before I code it up as a PR to phoenix.

**Comment by josevalim** [comment]
@aaronrenner it looks great. I wonder though if we need to do something with the test on line 25 for the context? maybe we should remove it and kill the `@valid_attrs`? WDYT?

**Comment by josevalim** [comment]
@aaronrenner alternatively, we do define a second function, called `valid_post_attributes()`, and re-use them on both fixtures, context and controller tests. I actually think I prefer this better and it is closer to what you first proposed. WDYT?

**Comment by aaronrenner** [comment]
@josevalim I do like the idea of removing `@valid_attrs`  and replacing it with a `valid_post_attributes` function call. However, since the valid attribute values are now defined in a separate file, it makes it difficult for the user to see why the attributes should equal the given values.

```elixir
    test "create_post/1 with valid data creates a post" do
      assert {:ok, %Post{} = post} = Blog.create_post(valid_post_attributes())
      assert post.body == "some body"
      assert post.rating == 42
      assert post.title == "some title"
    end
```

What do you think about storing the attributes in a variable and then using the attributes variable in the assertion?

```elixir
    test "create_post/1 with valid data creates a post" do
      valid_attrs = valid_post_attributes()

      assert {:ok, %Post{} = post} = Blog.create_post(valid_attrs)

      assert post.body == valid_attrs.body
      assert post.rating == valid_attrs.rating
      assert post.title == valid_attrs.title
    end
```

**Comment by josevalim** [comment]
Ah, that's a good point. Unfortunately, I am not a big fan of:

```elixir
    test "create_post/1 with valid data creates a post" do
      valid_attrs = valid_post_attributes()

      assert {:ok, %Post{} = post} = Blog.create_post(valid_attrs)

      assert post.body == valid_attrs.body
      assert post.rating == valid_attrs.rating
      assert post.title == valid_attrs.title
    end
```

Because it makes the test harder to read. So maybe it is best to get rid of the test that uses @valid_attrs altogether? The fixture itself already tests it... but I am not sure. WDYT?

**Comment by aaronrenner** [comment]
I see what you mean that it makes things harder to read. If we remove this test,

```elixir
    test "create_post/1 with valid data creates a post" do
      assert {:ok, %Post{} = post} = Blog.create_post(@valid_attrs)
      assert post.body == "some body"
      assert post.rating == 42
      assert post.title == "some title"
    end
```
I can't find anywhere else that ensures all of the attributes are set as expected on `create_post/1`. The following tests do use the `post_fixture/0`, which calls `create_post/1`, but don't actually assert that all of the fields are being set that I think are being set:

```elixir
    test "list_posts/0 returns all posts" do
      post = post_fixture()
      assert Blog.list_posts() == [post]
    end

    test "get_post!/1 returns the post with given id" do
      post = post_fixture()
      assert Blog.get_post!(post.id) == post
    end
```
So after thinking about it more, I'm personally leaning toward limiting the fixture-related generator changes to the current diff in this PR. What do you think? If it looks good, I'll start working on the PR to phoenix.

P.S. Thanks so much for taking the time to discuss this with me! Better to figure it out now than after I spent time to update the generators. :smile:

**Comment by josevalim** [comment]
Yeah, I agree then it is best to ship this PR as is. Perhaps what we should do is to actually remove the module attributes. The first two are only used once, so there is no benefit, and the invalid attrs is easy to replicate.

**Comment by aaronrenner** [comment]
Ah, yes. I see what you're saying about removing those module attributes and updated the PR. :+1: 

I started to remove `@create_attrs` and `@update_attrs` in `post_live_test.exs`, but realized `@update_attrs` is used in 2 places, so I decided to leave it and thought it would be inconsistent to store `@update_attrs` in a module attribute and have `create_attrs` declared in the test.

I'm going to start on the Phoenix PR, but if you see any additional changes, it will be easy to update.

**Comment by josevalim** [comment]
Agreed. Thanks! :heart:

**Pull request closed without merging**
